config/routes.rb
Rails.application.routes.draw do
  root "albums#index"
  resources :pictures
  resources :albums do
    get "image_list" => "albums#image_list", :defaults => { format: 'json'}
  end
  get "image_list" => "albums#image_list", :defaults => { format: 'json'}

end

app/models/album.rb
class Album < ActiveRecord::Base
  has_many :pictures, dependent: :destroy

  attr_accessor :images, :title, :description

  def images=(files)
    if files
      files.each do |file|
        pictures.build(image: file.pop)
      end
    end
  end
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :album
  mount_uploader :image, ImageUploader
  before_save :update_image_attributes

  # rename json thumbnail url to just path instead of image.thumb.url
  def path
    image.thumb.url
  end

  # rename image_file_name and image_file_size to be used on javascript
  def as_json(options = { })
    h = super(options)
    h["name"] = h.delete "image_file_name"
    h["size"] = h.delete "image_file_size"
    h
  end

  private
    def update_image_attributes
      if image.present? && image_changed?
        self.image_file_size = image.file.size
        self.image_file_name = image.file.filename
      end
    end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    @albums = Album.all
    @pictures = Picture.all
  end

  # localhost:3000/albums/1/image_list.json, this is
  # for dropzone thumbnail previews
  def image_list
    @images = Picture.where(album_id: params[:album_id])
    respond_to do |format|
      format.json { render json: @images.to_json(methods: [:path])}
    end
  end

  def new
    @album = Album.new
  end

  def create
    @album = Album.create(album_params)
    respond_to do |format|
      if @album.save
        format.html { redirect_to root_path, notice: 'Album was successfully created.' }
        format.js
        format.json { render json: { message: "success", fileID: @album.id}, :status => 200 }
      else
        render 'new'
      end
    end
  end

  def edit
    @album = Album.find(params[:id])
  end

  def update
    @album = Album.find(params[:id])
    respond_to do |format|
      if @album.update_attributes(album_params)
        format.html { redirect_to root_path, notice: 'Album was successfully created.' }
        format.json { render json: @album  }
        format.js {}
      else
        flash[:danger] = "Album has not been saved."
        render 'new'
      end
    end
  end

  def destroy
    @album = Album.find(params[:id])
    if @album.destroy
      flash[:notice] = "Album has been deleted"
      redirect_to root_path
    end
  end

  def show
    @album = Album.find(params[:id])
      respond_to do |format|
        format.json { render json: @album }
      end
  end

  private

  def album_params
    params.require(:album).permit(:name,:title,:description).tap do |whitelisted|
      whitelisted[:images] = params[:album][:images]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def index
    @pictures = Picture.all
  end

  def edit
    @picture = Picture.find(params[:id])
  end

  def destroy
    picture = Picture.find(params[:id])
    if picture.destroy
      render json: { message: "file deleted from server" }
    end
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
  def current_url(new_params)
    params.merge!(new_params)
    string = params.map{ |k,v| "#{k}=#{v}" }.join("&")
    request.uri.split("?")[0] + "?" + string
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/albums/_edit.html.slim
div data-remodal-id="modal"
  = link_to "Delete Album", @album, :method => :delete
  = render 'form'

app/views/albums/_form.html.slim
= simple_form_for @album, remote: true, :authenticity_token => true,
  :html => { multipart: true, id:"my-dropzone", class:"dropzone form-horizontal" } do |f|
  = f.input :name, class: "form-control"
  = f.input :title, class: "form-control"
  = f.input :description, class: "form-control"

  #template
    .dz-preview.dz-image-preview
      .dz-image
        img(data-dz-thumbnail)
      .dz-details
        .dz-size
          span(data-dz-size)
        .dz-filename
          span(data-dz-name)
      .dz-progress
        span.dz-upload(data-dz-uploadprogress)
      .dz-error-message
        span(data-dz-errormessage)
      .dz-success-mark
      .dz-error-mark

  .fallback
    = f.input :images, as: :file, input_html: {multipart: true }

  = f.button "submit", class: "btn btn-primary item-submit"

app/views/albums/_new.html.slim
div data-remodal-id="modal"
  = render "form"

app/views/albums/_photo.html.slim
.pswp tabindex='-1' role='dialog' aria-hidden='true'
  .pswp__bg
  .pswp__scroll-wrap
    .pswp__container
      .pswp__item
      .pswp__item
      .pswp__item
    .pswp__ui.pswp__ui--hidden
      .pswp__top-bar
        .pswp__counter
        button.pswp__button.pswp__button--close title='Close (Esc)'
        button.pswp__button.pswp__button--share title='Share'
        button.pswp__button.pswp__button--fs title='Toggle fullscreen'
        button.pswp__button.pswp__button--zoom title='Zoom in/out'
        .pswp__preloader
          .pswp__preloader__icn
            .pswp__preloader__cut
              .pswp__preloader__donut
      .pswp__share-modal.pswp__share-modal--hidden.pswp__single-tap
        .pswp__share-tooltip
      button.pswp__button.pswp__button--arrow--left title='Previous (arrow left)'
      button.pswp__button.pswp__button--arrow--right title='Next (arrow right)'
      .pswp__caption
            .pswp__caption__center

app/views/albums/edit.js.erb
$("#dropzone").html("<%= escape_javascript(render 'edit') %>")
$("#dropzone").addClass("update")

app/views/albums/index.html.slim
.row
  - @albums.each do |album|
    .col-md-3.slide
      .picture(itemscope itemtype="http://schema.org/ImageGallery")
        - album.pictures.each_with_index do |picture, i|
          - if picture.album_id == album.id
            figure(itemprop='associatedMedia' itemscope itemtype="http://schema.org/ImageObject")
              a(href="#{picture.image_url()}" itemprop="contentUrl" data-size="#{picture.width}x#{picture.height}")
                = image_tag picture.image_url(:medium) if i == 0
      = link_to "Edit", edit_album_path(album), remote: true, class: "edit"

= render "photo"

#dropzone

app/views/albums/new.js.erb
$("#dropzone").html("<%= escape_javascript(render 'new') %>")
$("#dropzone").removeClass("update")

app/views/albums/show.html.slim
= @album.name

app/views/layouts/application.html.slim
doctype html
html
  head
    title Dropzone Photoswip Sample Gallery
    == stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    == csrf_meta_tags

  body
    nav.navbar.navbar-default
      .container
        .navbar-header
          .navbar-brand href="#" Gallery

        ul.nav.navbar-nav
          li.active
            = link_to "Home", root_path
          li
            = link_to "Gallery", pictures_path
        ul.nav.navbar-nav.pull-right
          li
            = link_to "Upload", new_album_path, remote: true, class: "upload"
    section
      .container
        - flash.each do |key, message|
          div class="alert alert-#{key}"
            = message

        == yield

    == javascript_include_tag 'application', 'data-turbolinks-track' => true

app/views/pictures/index.html.slim
.row
  - @pictures.each do |picture|
    .col-md-3.slide
      .picture
        = image_tag picture.image_url(:medium)
      = link_to "Edit", edit_picture_path(picture)
      = link_to "Delete", picture, method: :delete